# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Orchestrate or schedule a set of jobs
jobs:
  build:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm run build
  test:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i 
      - run: npm run test
  analyze:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm run lint  
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
